trigger: none

pool:
  vmImage: ubuntu-latest

steps:
- task: AzureFunctionApp@2
  inputs:
    connectedServiceNameARM: ''
    appType: 'functionAppLinux'
    appName: 'iwb-mwbh-func-sandbox-connectivity'
    package: '$(System.DefaultWorkingDirectory)/**/*.zip'
    runtimeStack: 'NODE|20'
    deploymentMethod: 'auto'
